#+title:  Dotfiles
#+author: Gerard
#+email:  gerrysoft@outlook.es

#+HTML_HEAD_EXTRA: <style> .TOC_2_org { display: none; } </style> \
#+options: toc:nil
#+property: header-args :results silent

This are my personal dotfiles for GNU/Linux, as well as useful scripts, located mostly in the =sc/= folder. Some of them are part of [[https://github.com/gerardet46/my-flybinds][my build of flybinds]], which are located in =sc/flybinds=.

It also includes my Emacs config!


* Installation
Just clone this repo in the *HOME* folder. Everything should work out of the box.
#+begin_src shell
  git clone "https://github.com/gerardet46/dotfiles" ~/
#+end_src

** Hooks for Arch Linux
If you are in an Arch linux based distro, you can prepare the =.config/pacman-hooks= executing (you will need to do this every time you create/delete/rename a /pacman hook/).
#+begin_src shell
.config/set-config.sh
#+end_src


* Notes
- Some configs are using my library [[https://github.com/gerardet46/gcolors][gcolors]] to set global colors for all the system, so the window manager may crash if you don't have those installed. This are the script files that uses colors, for example =$COL_BG_0=, so maybe you can search for those files containing color definitions by executing =grep -R "COL_" * .[^.]*.=
- For setting up Emacs, you can read the literate config (actually the README.org) in the =.emacs.d= folder.
- The file =copyconfigs.sh= is used by me to rsync all the configs I need to upload.
