#!/usr/bin/env sh

alias ..='cd ..'
alias ...='cd ../..'
alias la='ls -a'
alias ll='ls -l'
alias l='ls -al'
alias sc='cd $HOME/sc/ ; $EDITOR "$(fzf)"; cd $HOME'
alias pkg='cd $HOME/pkg/ ; $EDITOR "$(fzf)"; cd $HOME'

# void
alias \
    xi="sudo xbps-install" \
    xq="xbps-query" \
    xqs="xbps-query -Rs" \
    xr="sudo xbps-remove -o"

# loginctl
alias \
    off="loginctl poweroff" \
    poweroff="loginctl poweroff" \
    reboot="loginctl reboot"

# newer programs
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"
[ -x "$(command -v nsxiv)" ] && alias sxiv="nsxiv"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="pkill" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	z="zathura" \
    yt="yt-dlp --embed-metadata" \
    ytaudio="yt-dlp --embed-metadata -f 'ba' -x --audio-format mp3"

