#!/usr/bin/env sh

# general
export TERMINAL="st"
export EDITOR="nvim"
export BROWSER="firefox"
export QT_QPA_PLATFORMTHEME="qt5ct"
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'

# less
export LESSHISTFILE="$HOME/.cache/lessht"
export LESS_TERMCAP_mb=$'\e[1;35m'
export LESS_TERMCAP_md=$'\e[1;35m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;32m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;34m'

