#!/bin/sh

# Això s'executa automàticament quan s'executa "startx".

# Carregam el nostre perfil
if [ -f "$HOME/.config/x11/xprofile" ]; then
	. "$HOME/.config/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

# Sessió per defecte
session=${1:-dwm}

# Iniciar sessió
case $session in
    dwm)
        dwmblocks &
        exec dwm
        ;;
    *) exec $session
esac
