#!/usr/bin/env sh

# Autostart
autostart="xcompmgr redshift nm-applet dunst emacs-daemon"

# Colors
. /opt/gcolors/colors_env.sh

# Xresources
"$HOME"/.config/x11/xresources.sh
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!

# Carrega dbus i altres
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Variables
export PATH="$PATH:$HOME/sc:$HOME/.local/bin"
export SUDO_ASKPASS="/usr/lib/ssh/x11-ssh-askpass"  # pacman -S x11-ssh-askpass

# Pantalla
monitors

# Fons d'escriptori
xwallpaper --zoom "$HOME/.config/wallpaper" &

# Teclat ES, ESC per Caps, ...
remaps &

# Autostart
for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
