#!/usr/bin/env sh

# Variables
export PATH="$PATH:$HOME/sc:$HOME/.local/bin"
#export SUDO_ASKPASS="/usr/lib/ssh/x11-ssh-askpass"  # pacman -S x11-ssh-askpass
export SUDO_ASKPASS="/usr/bin/lxqt-openssh-askpass"  # pacman -S x11-ssh-askpass

# Set and refresh colors. Also load Xresources
# Set theme name in ~/.config/theme
# Available themes:
# - nord
# - dracula
# - gruvbox-dark
theme="$(cat "$HOME/.config/theme" || echo nord)"
. "$HOME/.config/shell/themes/env/$theme.sh"
colorrefresh

unset theme

# Carrega Xresources
xrdb "$HOME/.config/x11/xresources" & xrdbpid=$!

# Carrega dbus i altres
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Pantalla
monitors

# Wallpaper
setwallpaper

# Teclat ES, ESC per Caps, ...
remaps &

# Pulseaudio
pulseaudio --daemonize=true --exit-idle-time=-1

# Autostart
autostart="xcompmgr sxhkd redshift nm-applet unclutter dunst emacs-daemon"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
