#!/usr/bin/sh

fitxer="$HOME/.config/bookmarks"

if [ -z "$1" ]; then
    # copiam el bookmark, amb dmenu
    nom="$(grep -v "^#" "$fitxer" | awk -F '|' '{print $1}' | dmenu -l 20 -p "Selecciona marcador")"
    grep -v "^#" "$fitxer" | grep "^$nom|" | awk -F '|' '{print $2}'
else
    # desam el bookmark $1
    if grep "|$1$" "$fitxer"; then
        notify-send "🔖 Marcador trobat" "$1"
    else
        nom="$(printf "" | dmenu -p "Nom del marcador:")"
        notify-send "🔖 Marcador desat" "$nom: $1"
        echo "$nom|$1" >> "$fitxer"
    fi
fi
