#!/usr/bin/sh

# refresh files that contain COLOR definitions

# check if we need to change the theme
if ! [ -z "$1" ]; then
    . "$HOME/.config/shell/themes/env/$1.sh"
    echo "$1" > "$HOME/.config/theme"
fi

# reload config files
while read f; do
    [ -f "$HOME/$f" ] && "$HOME/$f" && echo "Fet - $f"
done <<EOF
.config/x11/xresources.sh
.config/dunst/dunstrc.sh
.config/zathura/zathurarc.sh
.gnupg/pinentry-dmenu.conf.sh
EOF
unset f

# Xresources
xrdb "$HOME"/.config/x11/xresources & xrdbpid=$!

# kill dunst if running
pidof dunst >/dev/null && killall dunst
