#!/bin/sh

# Per muntar i desmuntar USB amb dmenu
# Dependències: dmenu, lsblk, pmount, udisks2

#muntats="$(lsblk -nrpo "name,type,size,mountpoint,label" | awk -F':' '{gsub(/ /,":")}$4!~/\/boot|\/efi|\/home$|SWAP/&&length($4)>1{printf "%s (%s) %s\n",$4,$3,$5}')"
#lsblk -nrpo "name,type,size,label" | grep "$(lsblk -nrpo "name,type,mountpoint" | awk '$2=="part" && $3 == "" {print $1}')" | dmenu

dev="$(lsblk -nro "type,name,size,mountpoint,label" \
	| cut -d " " -f 2- \
	| dmenu -l 20 -p "Selecciona Dispositiu" \
	| awk '{print $1}')"

[ -z "$dev" ] && exit 1

dev="/dev/$dev"
if grep -qs "$dev " /proc/mounts; then
	# està muntat, el demuntam
	sync
	if pumount "$dev"; then
		notify-send "$dev desmuntat"
		udisksctl power-off -b "$dev" && notify-send "$dev apagat" || notify-send "Error al apagar $dev"
	else
		notify-send "Error al desmuntar $dev"
	fi
else
	# si no està muntat, el muntam
	pmount "$dev"
	notify-send "$dev muntat a $(lsblk -n "$dev" | rev | cut -d' ' -f1 | rev)"
fi
