#!/usr/bin/sh

if [ -z "$1" ]; then
    echo "Ús:"
    echo "---------------------------------------------------------"
    echo "add        afegeix una finestra a tabbed        (xdotool)"
    echo "add-dm     afegeix una finestra a tabbed        (dmenu)"
    echo "create     crea una instància amb una finestra  (xdotool)"
    echo "create-dm  crea una instància amb una finestra  (dmenu)"
    echo "del        elimina finestra principal de tabbed (xdotool)"
    echo "del-dm     elimina finestra principal de tabbed (dmenu)"
fi

DMENU="dmenu -l 20"

select() {
    xdotool selectwindow
}

select_dm() {
    xprop -root \
        | grep ^_NET_CLIENT_LIST \
        | sed 's/.*\# //' \
        | sed 's/, /\n/g' >/tmp/tabc-clients2

    [ -f /tmp/tabc-clients ] && rm /tmp/tabc-clients

    # process list with names
    while read w; do
        echo "[$w]  $(xdotool getwindowname "$w")" >> /tmp/tabc-clients
    done </tmp/tabc-clients2
    rm /tmp/tabc-clients2

    # dmenu the list
    echo "$(cat /tmp/tabc-clients \
        | $DMENU -p "Selecciona una finestra" \
        | grep -o "^.*\]" \
        | tr -d "[]")"
}

get_tabbed_id() {
    xwininfo -root -children | grep tabbed | awk '{print $1}'
}
    

case "$1" in
    add)
        notify-send "Selecciona:" "1. Finestra\n2. Tabbed"
        tabc add "$(select)" "$(select)"
        ;;
    add-dm)
        tabc add "$(select_dm)" "$(get_tabbed_id | $DMENU -p "Selecciona tabbed")"
        ;;
    create)
        tabc create "$(select)"
        ;;
    create-dm)
        tabc create "$(select_dm)"
        ;;
    del)
        tabbedid="$(get_tabbed_id)"
        if [ "$(echo "$tabbedid" | wc -l)" = "1" ]; then
            tabc remove-child "$tabbedid"
        else
            tabc remove-child "$(select)"
        fi
        ;;
    del-dm)
        tabbedid="$(get_tabbed_id)"
        if [ "$(echo "$tabbedid" | wc -l)" = "1" ]; then
            tabc remove-child "$tabbedid"
        else
            tabc remove-child "$(get_tabbed_id | $DMENU -p "Selecciona tabbed")"
        fi
        ;;
esac

