#!/bin/sh

# read emoji list and pipe it to dmenu
file="$HOME/sc/emoji_list"
list=$(sed 's/|\:[^\:]\+:|/ /' "$file" | tr '[:upper:]' '[:lower:]')

# copy and insert emoji
emo="$(echo "$list" | dmenu -p "Copiar emoji" -l 20 | awk '{print $1}')"
echo "$emo" | tr -d '\n' | xclip -selection clipboard
xdotool type "$emo"
#pgrep -x dunst >/dev/null && notify-send "$(xclip -o -selection clipboard) s'ha copiat."
