#!/usr/bin/env python

import sys

sys.argv.pop(0)
if not sys.argv:
    print("Ús: rgb2hex col1 col2 ...", file=sys.stderr)
    exit(1)

for col in sys.argv:
    c = col.lstrip('#')
    print(f"{col} rgb{tuple(int(c[i:i+2], 16) for i in (0, 2, 4))}")
