#!/usr/bin/env python

import sys

sys.argv.pop(0)
if not sys.argv:
    print("Ús: rgb2hex col1 col2 ...", file=sys.stderr)
    exit(1)

cols = sys.argv
op = 1

try:
    op = float(sys.argv[0])
    cols = sys.argv[1:]
except ValueError:
    pass

for col in cols:
    c = col.lstrip('#')
    rgb = [int(c[i:i+2], 16) for i in (0, 2, 4)]
    text = "rgb"
    if op < 1 and op >= 0:
        rgb.append(op)
        text += "a"

    print(f"{col} {text}{tuple(rgb)}")
