#!/usr/bin/sh

if [ -z "$1" ]; then
    echo "---------- XDOTOOL"
    echo "create     crea una instància         "
    echo "add        afegeix finestres          "
    echo "del        elimina finestra principal "
    echo "del-all    elimina totes les finestres"
    echo "---------- DMENU"
    echo "create-dm  crea una instància         "
    echo "add-dm     afegeix finestres          "
    echo "del-dm     elimina finestra principal "
fi

DMENU="dmenu -l 20"

select() {
    xdotool selectwindow
}

select_dm() {
    xprop -root \
        | grep ^_NET_CLIENT_LIST \
        | sed 's/.*\# //' \
        | sed 's/, /\n/g' >/tmp/tabc-clients2

    [ -f /tmp/tabc-clients ] && rm /tmp/tabc-clients

    # process list with names
    while read w; do
        echo "[$w]  $(xdotool getwindowname "$w")" >> /tmp/tabc-clients
    done </tmp/tabc-clients2
    rm /tmp/tabc-clients2

    # dmenu the list
    echo "$(cat /tmp/tabc-clients \
        | $DMENU -p "Selecciona una finestra" \
        | grep -o "^.*\]" \
        | tr -d "[]")"
}

get_tabbed_id() {
    xwininfo -root -children | grep tabbed | awk '{print $1}'
}
    

case "$1" in
    add)
        tabbedid="$(get_tabbed_id)"
        if ! [ "$(echo "$tabbedid" | wc -l)" = "1" ]; then
            notify-send "Selecciona:" "1. Tabbed\n2. Finestres"
            tabbedid="$(select)"
        else
            notify-send "Selecciona finestres a afegir"
        fi
        wid=$(select)
        while xdotool windowreparent $wid $tabbedid 2>/dev/null; do
            wid=$(select)
        done
        ;;
    add-dm)
        tabbedid="$(get_tabbed_id)"
        if ! [ "$(echo "$tabbedid" | wc -l)" = "1" ]; then
            tabbedid="$(get_tabbed_id | $DMENU -p "Selecciona tabbed")"
            [ -z "$tabbedid" ] && exit 1
        fi
        wid=$(select_dm)
        while xdotool windowreparent $wid $tabbedid 2>/dev/null; do
            wid=$(select_dm)
        done
        ;;
    create)
        tabbedid=$(tabbed -d -c -k)
        wid=$(select)
        while xdotool windowreparent $wid $tabbedid 2>/dev/null; do
            wid=$(select)
        done
        ;;
    create-dm)
        tabbedid=$(tabbed -d -c -k)
        wid=$(select_dm)
        while xdotool windowreparent $wid $tabbedid 2>/dev/null; do
            wid=$(select_dm)
        done
        ;;
    del)    dm-tabc del ;;
    del-dm) dm-tabc del-dm ;;
    del-all)
        tabbedid="$(get_tabbed_id)"
        if ! [ "$(echo "$tabbedid" | wc -l)" = "1" ]; then
            tabbedid="$(select)"
        fi
        while tabc remove-child "$tabbedid" 2>/dev/null; do
            a=2 # nothing
        done
        ;;
esac
