#!/usr/bin/env sh

# options
# no, list, path, help

fromlist() {
    # fons de /usr/share/wallpaper (separats per \n)
    # que volem fer servir (se'n triarà un aleatori)
    fons="0216\n0195\n0271\nma1\nma2"

    # Seleccionam un fons d'escriptori aleatori.
    printf "$fons" \
        | sort -R \
        | head -1 \
        | while read line; do
        cp -r /usr/share/wallpapers/"$line".jpg "$HOME/.config/wallpaper"
    done

    # Ho posam de fons d'escriptori
    xwallpaper --zoom "$HOME/.config/wallpaper" &
}

frompath() {
    #sel="$(ls /usr/share/wallpapers | shuf -n 1)"
    #cp -r "/usr/share/wallpapers/$sel" "$HOME/.config/wallpaper"
    xwallpaper --zoom "$HOME/.config/wallpaper" &
}

case "$1" in
    "no") xwallpaper --clear ;;
    "list") fromlist ;;
    "path") frompath ;;
    "help") echo "setwallpaper no|list|path" ;;
    *) frompath ;;
esac
