#!/usr/bin/env sh

case "$1" in
    testpush) rclone sync --dry-run "$HOME/nxc" sftp: ;;
    testpull) rclone sync --dry-run sftp: "$HOME/nxc" ;;
    push) rclone sync -v --stats-one-line -P "$HOME/nxc" sftp: ;;
    pull) rclone sync -v --stats-one-line -P sftp: "$HOME/nxc" ;;
    *)
    echo "Ús: srv [push|pull|testpush|testpull]"
    echo "   push:     de local a servidor"
    echo "   pull:     de servidor a local"
    echo "   testpush: prova de local a servidor"
    echo "   testpull: prova de servidor a local"
    exit 1
    ;;
esac
