#!/usr/bin/env sh

# aquest script utiliza "mpc"

case "$BLOCK_BUTTON" in
    1) mpc toggle ;;
    3) mpc next   ;;
esac

mpc >/dev/null 2>&1 || exit 0

# ses dades són a partir de sa 2na columna
durada=$(mpc status | sed -n 2p | awk -F '/' '{print $NF}' | cut -d' ' -f1)
cur="$(mpc current)"
text="$durada $cur"
icon=$(mpc | grep "\[playing\]" > /dev/null && echo "" || echo "")

if [ -n "$cur" ]; then
    echo "^c$COL_VERD^$icon   $text"
else
    echo "^c$COL_BG_0^-"
fi
