#!/usr/bin/env sh

case "$1" in
    a) sudo poweroff ;;
    r) sudo reboot ;;
    b) slock & xset dpms force off ;;
    h) slock loginctl hibernate ;;
    s) slock loginctl "suspend" ;;
    x) i3-msg exit || killall dwm ;;
esac
