#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

rotate() {
	degree="$1"
	#tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
	#	case "$(file -b -i "$file")" in
		#image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
	#	*)           mogrify  -rotate "$degree" "$file" ;;
	#	esac
	#done
	mogrify  -rotate "$degree" "$2"
}

# eliminar
if [ "$1" = "r" ] && [ "$(printf "Sí\nNo" | dmenu -p "Eliminar imatge(s)?")" = "Sí" ]; then
    while read file
    do
        rm -f "$file"
    done
elif [ "$1" = "d" ]; then
    while read file
    do
        echo "$file"
    done | xargs -d '\n' dragon-drop -a -x
elif [ "$1" = "C" ]; then
    while read file
    do
        echo "$file"
    done | xclip -selection clipboard
fi

while read file
do
    fullpath="$(pwd)/$file"
    [ "$(echo "$file" | cut -c1-1)" = "/" ] && fullpath="$file"
    case "$1" in
        "w")
            cp -r "$file" $HOME/.config/wallpaper
            xwallpaper --zoom $HOME/.config/wallpaper
            ;;
        "y")      echo -n "$fullpath" | xclip -in -selection clipboard ;;
        "c")      xclip -selection clipboard -target image/png "$file" ;;
        "g")      gimp "$fullpath" & ;;
        "comma")  rotate 270 "$fullpath" ;;
        "period") rotate  90 "$fullpath" ;;
        "slash")  rotate 180 "$fullpath" ;;
    esac
done
