#!/usr/bin/env sh

case "$1" in
    "m") st -e pulsemixer ;;
    "1") pactl set-card-profile 0 output:analog-stereo+input:analog-stereo ;;
    #"2") pactl set-card-profile 0 output:hdmi-stereo-extra1+input:analog-stereo ;;
    "2") pactl set-card-profile 0 output:hdmi-stereo+input:analog-stereo ;;
esac
