#!/usr/bin/env sh

_browser() {
    B=${BROWSER:-xdg-open}
    [ -z "$1" ] || $B "$@" &
}

_telegram() {
    which telegram-desktop >/dev/null && setsid  telegram-desktop || setsid /opt/Telegram/Telegram
}

_main() {
    case "$@" in
        w) setsid $BROWSER & ;;
        f) setsid st -e nnn ;;
        d) setsid dm-browse ;;
        t) _telegram ;;
        m) setsid st -e neomutt ; pkill -RTMIN+12 dwmblocks ;;
        e) setsid emacsclient -c ;;
        c) setsid st -e calcurse ;;
    esac
}

_main "$@" &
