#!/usr/bin/env sh

case "$1" in
    a) loginctl poweroff ;;
    r) loginctl reboot ;;
    b) slock & xset dpms force off ;;
    h) slock loginctl hibernate ;;
    s) slock loginctl suspend ;;
    x) i3-msg exit || killall dwm ;;
esac
