#!/usr/bin/env sh

tab="inf-tabc"

case "$@" in
    a) "$tab" add ;;
    A) "$tab" add-dm ;;
    c) "$tab" create ;;
    C) "$tab" create-dm ;;
    d) "$tab" del ;;
    D) "$tab" del-dm ;;
    x) "$tab" del-all ;;
esac
